apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-persistent-volume
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data/" # you should create this path on your local machine and give 777 permission
